### ISSUE TITLE
Why not add the releases?

### ISSUE THREAD

**Issue by shierru** [openmultiplayer/compiler#7]
Why not add version 3.10.11 and beyond as releases?

Currently the compiler comes with the open.mp server along with **qawno** (**_Windows version only_**). 

Why not add releases to this repository, where there will be only the compiler itself, built for windows and linux.

It will be much more convenient to get the compiler in **Github Actions** and use it there. As it is, I have to get the whole **open.mp** server and do a lot of manipulations to get only the compiler executables.

**Comment by ChronosXYZ** [comment]
You can check my [repo](https://github.com/ChronosXYZ/pawn-compiler-binary) as a temporary solution, I built compiler from the sources for Linux and Windows.

You can add configuration to use that repo in your `pawn.yaml`:
```yaml
builds:
    - name: main
      compiler:
          site: github.com
          user: ChronosXYZ
          repo: pawn-compiler-binary
          version: 3.10.11
```
